defines:
  filesystem: /home/muut/Documents/research/nvidiaAuto/alpasim/data
  driver_model: ???
  mpc_implementation: linear
  drivers: /home/muut/Documents/research/nvidiaAuto/alpasim/data/drivers
  sensordata: /home/muut/Documents/research/nvidiaAuto/alpasim/data/nre-artifacts
  alpackages: /home/muut/Documents/research/nvidiaAuto/alpasim/data/alpackages
  trafficsim_map_cache: /home/muut/Documents/research/nvidiaAuto/alpasim/data/trafficsim/unified_data_cache
  helper: scripts
  vscode: sources/remote-vscode-server
  nre_cache_size: '4'
  physics_cache_size: '16'
wizard:
  run_name: null
  run_method: DOCKER_COMPOSE
  run_mode: BATCH
  log_level: INFO
  description: unspecified
  submitter: unspecified
  latest_symlink: false
  log_dir: /home/muut/Documents/research/nvidiaAuto/alpasim/src/wizard/tutorial
  array_job_dir: null
  dry_run: false
  baseport: 6000
  validate_mount_points: true
  driver_code_hash: null
  driver_code_repo: null
  helper: ???
  vscode: ???
  sqshcaches:
  - /home/muut/Documents/research/nvidiaAuto/alpasim/data/sqsh
  - /home/muut/Documents/research/nvidiaAuto/alpasim/data/sqsh/dev
  slurm_job_id: 0
  timeout: 600
  nr_retries: 3
  run_sim_services:
  - driver
  - sensorsim
  - physics
  - trafficsim
  - controller
  - runtime
  debug_flags:
    use_localhost: false
  slurm_gpu_partition: null
  slurm_cpu_partition: cpu_short
  external_services: null
scenes:
  scene_ids:
  - clipgt-825dc886-0491-482a-abe3-e1743f5972b8
  test_suite_id: null
  limit_to_first_n: 0
  scene_cache: /home/muut/Documents/research/nvidiaAuto/alpasim/data/nre-artifacts
  scenes_csv:
  - /home/muut/Documents/research/nvidiaAuto/alpasim/data/scenes/sim_scenes.csv
  suites_csv:
  - /home/muut/Documents/research/nvidiaAuto/alpasim/data/scenes/sim_suites.csv
  sceneset_path: scenesets/208cadefc43065a8eac16ff4ed9d96c5
  local_usdz_dir: null
  nre_version_string: null
services:
  driver:
    volumes:
    - /home/muut/Documents/research/nvidiaAuto/alpasim/data/drivers:/mnt/drivers
    - /home/muut/Documents/research/nvidiaAuto/alpasim/src/wizard/tutorial:/mnt/output
    - /home/muut/Documents/research/nvidiaAuto/alpasim/src:/repo/src
    - /home/muut/.cache/huggingface:/root/.cache/huggingface
    image: alpasim-base:0.1.4
    external_image: false
    command:
    - uv run -m alpasim_driver.main
    - --config-path=/mnt/output
    - --config-name=driver-config.yaml
    - host=0.0.0.0
    - port={port}
    replicas_per_container: 1
    gpus:
    - 0
    environments: []
    workdir: null
    remap_root: false
  sensorsim:
    volumes:
    - /home/muut/Documents/research/nvidiaAuto/alpasim/data/nre-artifacts:/mnt/nre-data
    - /home/muut/Documents/research/nvidiaAuto/alpasim/data/nre-artifacts/ego-hoods:/mnt/ego-hoods
    image: docker.io/carlasimulator/nvidia-nurec-grpc:0.2.0
    external_image: true
    command:
    - /app/pycena_run.runfiles/nre_repo/scripts/pycena/runtime/entrypoint_3_11.sh
    - --port={port}
    - --host=0.0.0.0
    - --artifact-glob=/mnt/nre-data/{sceneset}/**/*.usdz
    - --egocar-hood-dir=/mnt/ego-hoods
    - --no-enable-nrend
    - --download-cache-dir /tmp/nre-cache-dir
    - --cache-size=4
    replicas_per_container: 1
    gpus:
    - 0
    environments:
    - OMP_NUM_THREADS=1
    workdir: null
    remap_root: false
  physics:
    volumes:
    - /home/muut/Documents/research/nvidiaAuto/alpasim/data/nre-artifacts:/mnt/nre-data
    - /home/muut/Documents/research/nvidiaAuto/alpasim/src:/repo/src
    - /home/muut/Documents/research/nvidiaAuto/alpasim/plugins:/repo/plugins
    image: alpasim-base:0.1.4
    external_image: false
    command:
    - uv run physics_server
    - --host=0.0.0.0
    - --port={port}
    - --artifact-glob=/mnt/nre-data/{sceneset}/**/*.usdz
    - --use-ground-mesh=true
    - --cache-size=16
    - --log-level=INFO
    replicas_per_container: 1
    gpus:
    - 0
    environments:
    - WARP_CACHE_PATH='/mnt/warp'
    workdir: null
    remap_root: false
  trafficsim:
    volumes: []
    image: alpasim-base:0.1.4
    external_image: false
    command:
    - echo 'not yet included'
    replicas_per_container: 1
    gpus:
    - 0
    environments: []
    workdir: null
    remap_root: false
  controller:
    volumes:
    - /home/muut/Documents/research/nvidiaAuto/alpasim/src/wizard/tutorial/controller:/mnt/output
    - /home/muut/Documents/research/nvidiaAuto/alpasim/src:/repo/src
    - /home/muut/Documents/research/nvidiaAuto/alpasim/plugins:/repo/plugins
    image: alpasim-base:0.1.4
    external_image: false
    command:
    - uv run python -m alpasim_controller.server
    - --port={port}
    - --log_dir=/mnt/output
    - --log-level=INFO
    replicas_per_container: 1
    gpus: null
    environments: []
    workdir: null
    remap_root: false
  runtime:
    volumes:
    - /home/muut/Documents/research/nvidiaAuto/alpasim/data/nre-artifacts:/mnt/nre-data
    - /home/muut/Documents/research/nvidiaAuto/alpasim/src/wizard/tutorial:/mnt/log_dir
    - /home/muut/Documents/research/nvidiaAuto/alpasim/src/wizard/tutorial:/mnt/array_job_dir
    - /home/muut/Documents/research/nvidiaAuto/alpasim/src:/repo/src
    - /home/muut/Documents/research/nvidiaAuto/alpasim/plugins:/repo/plugins
    image: alpasim-base:0.1.4
    external_image: false
    command:
    - uv run python -m alpasim_runtime.simulate
    - --usdz-glob=/mnt/nre-data/{sceneset}/**/*.usdz
    - --user-config=/mnt/log_dir/{runtime_config_name}
    - --network-config=/mnt/log_dir/generated-network-config.yaml
    - --log-dir=/mnt/log_dir
    - --log-level=INFO
    - --array-job-dir=/mnt/array_job_dir
    - --eval-config=/mnt/log_dir/eval-config.yaml
    replicas_per_container: 1
    gpus: null
    environments: []
    workdir: null
    remap_root: false
    depends_on:
    - driver
    - sensorsim
    - physics
    - trafficsim
    - controller
runtime:
  nr_workers: 1
  endpoints:
    sensorsim:
      n_concurrent_rollouts: 2
    driver:
      n_concurrent_rollouts: 14
    physics:
      n_concurrent_rollouts: 14
      skip: false
    controller:
      n_concurrent_rollouts: 14
      skip: false
    trafficsim:
      n_concurrent_rollouts: 14
      skip: true
    do_shutdown: true
    sensorsim_cache_size: '4'
  enable_autoresume: false
  artifact_cache_size: 10
  simulation_config:
    n_sim_steps: 100
    n_rollouts: 1
    force_gt_duration_us: 3000000
    send_recording_ground_truth: false
    control_timestep_us: 500000
    pose_reporting_interval_us: 0
    time_start_offset_us: 500000
    ego_mask_rig_config_id: null
    planner_delay_us: 0
    min_traffic_duration_us: 3000000
    assert_zero_decision_delay: true
    physics_update_mode: EGO_ONLY
    route_generator_type: MAP
    vehicle: null
    cameras:
    - height: 1080
      width: 1920
      logical_id: camera_front_wide_120fov
      frame_interval_us: 500000
      shutter_duration_us: 30000
      first_frame_offset_us: -30000
  extra_cameras:
  - logical_id: camera_front_wide_120fov
    rig_to_camera:
      translation_m:
      - 1.65897811
      - -0.01443456
      - 1.51539499
      rotation_xyzw:
      - -0.49929397355810856
      - 0.5039939168301356
      - -0.4972939976976715
      - 0.49939397235113037
trafficsim: {}
eval:
  enabled: true
  vec_map:
    incl_road_edges: true
    incl_traffic_signs: true
    incl_wait_lines: true
    max_num_lanes: 20
    num_pts_per_lane: 20
  num_processes: 16
  vehicle:
    vehicle_corner_roundness: 0.5
    vehicle_shrink_factor: 0.02
  scorers:
    min_ade:
      time_deltas:
      - 0.5
      - 1.0
      - 2.5
      - 5.0
      incl_z: false
      target: GT
    plan_deviation:
      incl_z: false
      avg_decay_rate: 0.1
      min_timesteps: 5
    image:
      camera_logical_id: camera_front_wide_120fov
  aggregation_modifiers:
    max_dist_to_gt_trajectory: 4.0
  video:
    render_video: true
    video_layouts:
    - DEFAULT
    camera_id_to_render: camera_front_wide_120fov
    reasoning_text_refresh_interval_s: 1.0
    overlay_plans_on_camera: true
    render_every_nth_frame: 1
    generate_combined_video: false
    combined_video_speed_factor: 0.33
    metrics_table_entries:
    - offroad_or_collision_at_fault
    - collision_any
    - collision_at_fault
    - collision_front
    - collision_lateral
    - collision_rear
    - offroad
    - dist_to_gt_trajectory
    - dist_to_gt_location
    - progress
    - progress_rel
    - safety_monitor_triggered
    map_video:
      map_radius_m: 20
      ego_loc: BOTTOM_CENTER
      rotate_map_to_ego: true
      map_elements_to_plot:
      - ROAD_LANE_CENTER
      - ROAD_LANE_LEFT_EDGE
      - ROAD_LANE_RIGHT_EDGE
      - ROAD_EDGE
      - STOP_LINE
      - GT_LINESTRING
      - EGO_GT_GHOST_POLYGON
      - DRIVER_RESPONSES
      - ROUTE
      - AGENTS
driver:
  log_level: INFO
  model:
    model_type: vam
    checkpoint_path: /mnt/drivers/vavam/VAM_width_1024_pretrained_139k.pt
    device: cuda
    tokenizer_path: /mnt/drivers/vavam/VQ_ds16_16384_llamagen_encoder.jit
  host: 0.0.0.0
  port: ???
  inference:
    use_cameras:
    - camera_front_wide_120fov
    max_batch_size: 32
    subsample_factor: 1
    context_length: 1
  rectification:
    camera_front_wide_120fov:
      focal_length:
      - 1545.0
      - 1545.0
      principal_point:
      - 960.0
      - 560.0
      resolution_hw:
      - 1080
      - 1920
      radial:
      - -0.356123
      - 0.172545
      - -0.05231
      - 0.0
      - 0.0
      - 0.0
      tangential:
      - -0.00213
      - 0.000464
      thin_prism:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      max_overscan_scale: 2.0
      safety_margin_px: 10
  route:
    default_command: 2
    use_waypoint_commands: true
    command_distance_threshold: 3.0
    min_lookahead_distance: 20.0
  output_dir: /mnt/output/driver
  trajectory_optimizer:
    enabled: false
  plot_debug_images: false
