description: unspecified
run_args: unknownArgs
run_dir: //home/muut/Documents/research/nvidiaAuto/alpasim/src/wizard/configs/custom_code
run_name: LR-b525a6a0-3bd6-4043-82e1-0cd62b0793c6
run_time: '2026-03-28 13:58:11'
run_user: muut
run_uuid: b525a6a0-3bd6-4043-82e1-0cd62b0793c6
slurm_job_id: 0
submitter: unspecified
test_suite_id: null
