defaults:
  - config_schema
  - _self_
defines:
  alpackages: /home/muut/Documents/research/nvidiaAuto/alpasim/data/alpackages
  driver_model: ???
  drivers: /home/muut/Documents/research/nvidiaAuto/alpasim/data/drivers
  filesystem: /home/muut/Documents/research/nvidiaAuto/alpasim/data
  helper: scripts
  mpc_implementation: linear
  nre_cache_size: '4'
  physics_cache_size: '16'
  sensordata: /home/muut/Documents/research/nvidiaAuto/alpasim/data/nre-artifacts
  trafficsim_map_cache: /home/muut/Documents/research/nvidiaAuto/alpasim/data/trafficsim/unified_data_cache
  vscode: sources/remote-vscode-server
driver:
  host: 0.0.0.0
  inference:
    max_batch_size: 16
    subsample_factor: 1
    use_cameras:
      - camera_cross_left_120fov
      - camera_front_wide_120fov
      - camera_cross_right_120fov
      - camera_rear_left_70fov
  log_level: INFO
  model:
    checkpoint_path: /mnt/drivers/transfuser/model_0060.pth
    device: cuda
    model_type: transfuser
  output_dir: /mnt/output/driver
  plot_debug_images: false
  port: ???
  rectification:
    camera_cross_left_120fov:
      focal_length:
        - 1545.0
        - 1545.0
      max_overscan_scale: 2.0
      principal_point:
        - 960.0
        - 560.0
      radial:
        - -0.356123
        - 0.172545
        - -0.05231
        - 0.0
        - 0.0
        - 0.0
      resolution_hw:
        - 1080
        - 1920
      safety_margin_px: 10
      tangential:
        - -0.00213
        - 0.000464
      thin_prism:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
    camera_cross_right_120fov:
      focal_length:
        - 1545.0
        - 1545.0
      max_overscan_scale: 2.0
      principal_point:
        - 960.0
        - 560.0
      radial:
        - -0.356123
        - 0.172545
        - -0.05231
        - 0.0
        - 0.0
        - 0.0
      resolution_hw:
        - 1080
        - 1920
      safety_margin_px: 10
      tangential:
        - -0.00213
        - 0.000464
      thin_prism:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
    camera_front_wide_120fov:
      focal_length:
        - 1545.0
        - 1545.0
      max_overscan_scale: 2.0
      principal_point:
        - 960.0
        - 560.0
      radial:
        - -0.356123
        - 0.172545
        - -0.05231
        - 0.0
        - 0.0
        - 0.0
      resolution_hw:
        - 1080
        - 1920
      safety_margin_px: 10
      tangential:
        - -0.00213
        - 0.000464
      thin_prism:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
    camera_rear_left_70fov:
      focal_length:
        - 1545.0
        - 1545.0
      max_overscan_scale: 2.0
      principal_point:
        - 960.0
        - 560.0
      radial: []
      resolution_hw:
        - 1080
        - 1920
      safety_margin_px: 10
      tangential: []
      thin_prism: []
  route:
    command_distance_threshold: 3.0
    default_command: 2
    min_lookahead_distance: 20.0
    use_waypoint_commands: true
  trajectory_optimizer:
    enabled: false
eval:
  aggregation_modifiers:
    max_dist_to_gt_trajectory: 4.0
  enabled: true
  num_processes: 16
  scorers:
    image:
      camera_logical_id: camera_front_wide_120fov
    min_ade:
      incl_z: false
      target: GT
      time_deltas:
        - 0.5
        - 1.0
        - 2.5
        - 5.0
    plan_deviation:
      avg_decay_rate: 0.1
      incl_z: false
      min_timesteps: 5
  vec_map:
    incl_road_edges: true
    incl_traffic_signs: true
    incl_wait_lines: true
    max_num_lanes: 20
    num_pts_per_lane: 20
  vehicle:
    vehicle_corner_roundness: 0.5
    vehicle_shrink_factor: 0.02
  video:
    camera_id_to_render: camera_front_wide_120fov
    combined_video_speed_factor: 0.33
    generate_combined_video: false
    map_video:
      ego_loc: BOTTOM_CENTER
      map_elements_to_plot:
        - ROAD_LANE_CENTER
        - ROAD_LANE_LEFT_EDGE
        - ROAD_LANE_RIGHT_EDGE
        - ROAD_EDGE
        - STOP_LINE
        - GT_LINESTRING
        - EGO_GT_GHOST_POLYGON
        - DRIVER_RESPONSES
        - ROUTE
        - AGENTS
      map_radius_m: 20
      rotate_map_to_ego: true
    metrics_table_entries:
      - offroad_or_collision_at_fault
      - collision_any
      - collision_at_fault
      - collision_front
      - collision_lateral
      - collision_rear
      - offroad
      - dist_to_gt_trajectory
      - dist_to_gt_location
      - progress
      - progress_rel
      - safety_monitor_triggered
    overlay_plans_on_camera: true
    reasoning_text_refresh_interval_s: 1.0
    render_every_nth_frame: 1
    render_video: true
    video_layouts:
      - DEFAULT
runtime:
  artifact_cache_size: 10
  enable_autoresume: false
  endpoints:
    controller:
      n_concurrent_rollouts: 14
      skip: false
    do_shutdown: true
    driver:
      n_concurrent_rollouts: 14
    physics:
      n_concurrent_rollouts: 14
      skip: false
    sensorsim:
      n_concurrent_rollouts: 2
    sensorsim_cache_size: '4'
    trafficsim:
      n_concurrent_rollouts: 14
      skip: true
  extra_cameras:
    - logical_id: camera_cross_left_120fov
      rig_to_camera:
        rotation_xyzw:
          - 0.679354
          - -0.207915
          - 0.215233
          - -0.670018
        translation_m:
          - 1.646354
          - 0.143369
          - 1.521469
    - logical_id: camera_front_wide_120fov
      rig_to_camera:
        rotation_xyzw:
          - 0.509222
          - -0.503331
          - 0.495086
          - -0.49218
        translation_m:
          - 1.6701
          - -0.025875
          - 1.522623
    - logical_id: camera_cross_right_120fov
      rig_to_camera:
        rotation_xyzw:
          - 0.205424
          - -0.674057
          - 0.676355
          - -0.214458
        translation_m:
          - 1.626168
          - -0.161517
          - 1.526269
    - logical_id: camera_rear_left_70fov
      rig_to_camera:
        rotation_xyzw:
          - 0.503851
          - 0.497823
          - -0.499723
          - -0.498582
        translation_m:
          - -0.486641
          - -0.000595
          - 1.486321
  nr_workers: 1
  simulation_config:
    assert_zero_decision_delay: true
    cameras:
      - first_frame_offset_us: -30000
        frame_interval_us: 250000
        height: 900
        logical_id: camera_cross_left_120fov
        shutter_duration_us: 30000
        width: 1600
      - first_frame_offset_us: -30000
        frame_interval_us: 250000
        height: 900
        logical_id: camera_front_wide_120fov
        shutter_duration_us: 30000
        width: 1600
      - first_frame_offset_us: -30000
        frame_interval_us: 250000
        height: 900
        logical_id: camera_cross_right_120fov
        shutter_duration_us: 30000
        width: 1600
      - first_frame_offset_us: -30000
        frame_interval_us: 250000
        height: 900
        logical_id: camera_rear_left_70fov
        shutter_duration_us: 30000
        width: 1600
    control_timestep_us: 250000
    ego_mask_rig_config_id: null
    force_gt_duration_us: 3000000
    min_traffic_duration_us: 3000000
    n_rollouts: 1
    n_sim_steps: 100
    physics_update_mode: EGO_ONLY
    planner_delay_us: 0
    pose_reporting_interval_us: 0
    route_generator_type: MAP
    send_recording_ground_truth: false
    time_start_offset_us: 250000
    vehicle: null
scenes:
  limit_to_first_n: 0
  local_usdz_dir: null
  nre_version_string: null
  scene_cache: /home/muut/Documents/research/nvidiaAuto/alpasim/data/nre-artifacts
  scene_ids:
    - clipgt-a309e228-26e1-423e-a44c-cb00aa7378cb
  scenes_csv:
    - /home/muut/Documents/research/nvidiaAuto/alpasim/data/scenes/sim_scenes.csv
  sceneset_path: scenesets/5f252ba230a9da476c64c7b8d0604af7
  suites_csv:
    - /home/muut/Documents/research/nvidiaAuto/alpasim/data/scenes/sim_suites.csv
  test_suite_id: null
services:
  controller:
    command:
      - uv run python -m alpasim_controller.server
      - --port={port}
      - --log_dir=/mnt/output
      - --log-level=INFO
    environments: []
    external_image: false
    gpus: null
    image: alpasim-base:0.1.4
    remap_root: false
    replicas_per_container: 1
    volumes:
      - //home/muut/Documents/research/nvidiaAuto/alpasim/src/wizard/configs/custom_code/tutorial_transfuser/controller:/mnt/output
      - /home/muut/Documents/research/nvidiaAuto/alpasim/src:/repo/src
      - /home/muut/Documents/research/nvidiaAuto/alpasim/plugins:/repo/plugins
    workdir: null
  driver:
    command:
      - uv run -m alpasim_driver.main
      - --config-path=/mnt/output
      - --config-name=driver-config.yaml
      - host=0.0.0.0
      - port={port}
    environments: []
    external_image: false
    gpus:
      - 0
    image: alpasim-base:0.1.4
    remap_root: false
    replicas_per_container: 1
    volumes:
      - /home/muut/Documents/research/nvidiaAuto/alpasim/data/drivers:/mnt/drivers
      - /home/muut/Documents/research/nvidiaAuto/alpasim/plugins:/repo/plugins
      - //home/muut/Documents/research/nvidiaAuto/alpasim/src/wizard/configs/custom_code/tutorial_transfuser:/mnt/output
      - /home/muut/Documents/research/nvidiaAuto/alpasim/src:/repo/src
      - /home/muut/.cache/huggingface:/root/.cache/huggingface
    workdir: null
  physics:
    command:
      - uv run physics_server
      - --host=0.0.0.0
      - --port={port}
      - --artifact-glob=/mnt/nre-data/{sceneset}/**/*.usdz
      - --use-ground-mesh=true
      - --cache-size=16
      - --log-level=INFO
    environments:
      - WARP_CACHE_PATH='/mnt/warp'
    external_image: false
    gpus:
      - 0
    image: alpasim-base:0.1.4
    remap_root: false
    replicas_per_container: 1
    volumes:
      - /home/muut/Documents/research/nvidiaAuto/alpasim/data/nre-artifacts:/mnt/nre-data
      - /home/muut/Documents/research/nvidiaAuto/alpasim/src:/repo/src
      - /home/muut/Documents/research/nvidiaAuto/alpasim/plugins:/repo/plugins
    workdir: null
  runtime:
    command:
      - uv run python -m alpasim_runtime.simulate
      - --usdz-glob=/mnt/nre-data/{sceneset}/**/*.usdz
      - --user-config=/mnt/log_dir/{runtime_config_name}
      - --network-config=/mnt/log_dir/generated-network-config.yaml
      - --log-dir=/mnt/log_dir
      - --log-level=INFO
      - --array-job-dir=/mnt/array_job_dir
      - --eval-config=/mnt/log_dir/eval-config.yaml
    depends_on:
      - driver
      - sensorsim
      - physics
      - trafficsim
      - controller
    environments: []
    external_image: false
    gpus: null
    image: alpasim-base:0.1.4
    remap_root: false
    replicas_per_container: 1
    volumes:
      - /home/muut/Documents/research/nvidiaAuto/alpasim/data/nre-artifacts:/mnt/nre-data
      - //home/muut/Documents/research/nvidiaAuto/alpasim/src/wizard/configs/custom_code/tutorial_transfuser:/mnt/log_dir
      - //home/muut/Documents/research/nvidiaAuto/alpasim/src/wizard/configs/custom_code/tutorial_transfuser:/mnt/array_job_dir
      - /home/muut/Documents/research/nvidiaAuto/alpasim/src:/repo/src
      - /home/muut/Documents/research/nvidiaAuto/alpasim/plugins:/repo/plugins
    workdir: null
  sensorsim:
    command:
      - /app/pycena_run.runfiles/nre_repo/scripts/pycena/runtime/entrypoint_3_11.sh
      - --port={port}
      - --host=0.0.0.0
      - --artifact-glob=/mnt/nre-data/{sceneset}/**/*.usdz
      - --egocar-hood-dir=/mnt/ego-hoods
      - --no-enable-nrend
      - --download-cache-dir /tmp/nre-cache-dir
      - --cache-size=4
    environments:
      - OMP_NUM_THREADS=1
    external_image: true
    gpus:
      - 0
    image: docker.io/carlasimulator/nvidia-nurec-grpc:0.2.0
    remap_root: false
    replicas_per_container: 1
    volumes:
      - /home/muut/Documents/research/nvidiaAuto/alpasim/data/nre-artifacts:/mnt/nre-data
      - /home/muut/Documents/research/nvidiaAuto/alpasim/data/nre-artifacts/ego-hoods:/mnt/ego-hoods
    workdir: null
  trafficsim:
    command:
      - echo 'not yet included'
    environments: []
    external_image: false
    gpus:
      - 0
    image: alpasim-base:0.1.4
    remap_root: false
    replicas_per_container: 1
    volumes: []
    workdir: null
trafficsim: {}
wizard:
  array_job_dir: null
  baseport: 6000
  debug_flags:
    use_localhost: false
  description: unspecified
  driver_code_hash: null
  driver_code_repo: null
  dry_run: false
  external_services: null
  helper: ???
  latest_symlink: false
  log_dir: //home/muut/Documents/research/nvidiaAuto/alpasim/src/wizard/configs/custom_code/tutorial_transfuser
  log_level: INFO
  nr_retries: 3
  run_method: DOCKER_COMPOSE
  run_mode: BATCH
  run_name: null
  run_sim_services:
    - driver
    - sensorsim
    - physics
    - trafficsim
    - controller
    - runtime
  slurm_cpu_partition: cpu_short
  slurm_gpu_partition: null
  slurm_job_id: 0
  sqshcaches:
    - /home/muut/Documents/research/nvidiaAuto/alpasim/data/sqsh
    - /home/muut/Documents/research/nvidiaAuto/alpasim/data/sqsh/dev
  submitter: unspecified
  timeout: 600
  validate_mount_points: true
  vscode: ???
